### PR TITLE
Add Murmur3 module with necessary hashString function

### LINKED ISSUE #12: Vendor in `Skinney/murmur3` to make this package usable again
We're currently getting these errors when installing packages in our application:

```
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for Skinney/murmur3 2.0.8 from:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it looks like the hash of the archive has changed since publication:

  Expected: 81a0bada79740ae806df04b1bb14a7d64f763ac5
    Actual: 931398ec656078e26b2e29520cd283ffe6e8e441
```

I don't know the cause, but all packages that have murmur3 as a dep are basically broken. A solution is to vendor in (i.e, copy the library code) from murmur3 into this package. This is what `elm-graphql` has done: https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-ELM-PACKAGE.md#502---2020-09-17

### PR DESCRIPTION
**Pull request by jjant**
Vendor in Murmur3's necessary function to fix #12.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Approach looks good! Would you mind inlining the license from that repo into the documentation comment at the top?

**Comment by jjant** [comment]
@rtfeldman Sure, done 👍.

**Comment by rtfeldman** [comment]
Published as `2.0.1`!

**Comment by rtfeldman** [comment]
Thanks for the PR!

**Comment by jjant** [comment]
Thanks Richard!

**Pull request merged**
